FROM richarvey/nginx-php-fpm:latest

# Copiamos todo el proyecto
COPY . /var/www/html

# Variables de entorno críticas
ENV SKIP_COMPOSER 0
ENV WEBROOT /var/www/html/public
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV APP_ENV production

# Instalamos dependencias de PHP
RUN composer install --no-dev --optimize-autoloader

# Configuración de Base de Datos y Permisos
RUN mkdir -p /var/www/html/database && \
    touch /var/www/html/database/database.sqlite && \
    chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache /var/www/html/database && \
    chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache /var/www/html/database

# TRUCO FINAL: Forzar la migración y el arranque correcto
ENV RUN_SCRIPTS 1
RUN mkdir -p /var/www/scripts && \
    echo "php /var/www/html/artisan migrate --force" > /var/www/scripts/run.sh && \
    chmod +x /var/www/scripts/run.sh

EXPOSE 80